apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: client
resources:
- namespace.yaml
- ../base/

patchesJson6902:
- path: hpa-patch.yaml
  target:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    name: client
    version: v2beta1

images:
- name: IMAGE_NAME
  newName: ghcr.io/terotuomala/client
  newTag: 5503fb8294c063b5f44f97f1c93be6abc13655cc
